#+title: Advent of Clerk
#+author: Marco Dalla Stella
#+date: \today

A repository containing my advent of code solutions; built in Clerk.

Those unfamiliar should read [[https://adventofcode.com/about][here]] but in short it's an annual programming puzzle
competition focused around [[https://en.wikipedia.org/wiki/Advent_calendar][the Advent]].

* Why Clerk?

For anyone that's used Clerk before, the answer should be obvious; but otherwise
Clerk is a notebook-style live programming environment for Clojure that also
renders comments in Markdown.

Without needing extra files (other than 1 index page) and adding in some
comments, I can export my namespaces as HTML pages with examples; and even use
custom HTML viewers.

Live is /truly/ live, within milliseconds of me saving my namespace the running
output (called by =bb serve=) updates with the computed result. Long-running
answers happen during evaluation time but as soon as that's done the page
updates. The instant feedback in this kind of environment is vital.

* Credits
- [[https://github.com/nextjournal/advent-of-clerk][Advent of Clerk]] of which this is based on
- [[https://github.com/elken/aoc][elken/aoc]] this is a fork of this repository 🙏
